title: "SakurakiRP – Documentation"
url: "https://sakurakirp.github.io"
baseurl: "/Documentation"

remote_theme: just-the-docs/just-the-docs
color_scheme: dark          # ← on force le dark natif, clair et net
plugins:
  - jekyll-remote-theme

search_enabled: true
logo: "/assets/img/Logo-SakurakiRP.png"
favicon_ico: "/assets/img/favicon.ico"

nav_external_links:
  - title: "Notre Support"
    url: "https://discord.gg/jy6g3CkGcW"
    hide_icon: false

footer_content: "© SakurakiRP — Documentation"