title: "SakurakiRP – Documentation"
url: "https://sakurakirp.github.io"
baseurl: "/Documentation"

remote_theme: just-the-docs/just-the-docs
color_scheme: dark
search_enabled: true
logo: "/assets/img/Logo-SakurakiRP.png"     # fournis ton logo
favicon_ico: "/assets/img/favicon.ico"

nav_external_links:
  - title: "Serveur Discord"
    url: "https://discord.gg/ton-invite"
    hide_icon: false

# Pied de page
footer_content: "© SakurakiRP — Documentation"