title: "SakurakiRP – Documentation"
url: "https://sakurakirp.github.io"
baseurl: "/Documentation"

remote_theme: just-the-docs/just-the-docs
search_enabled: true
color_scheme: dark          # light | dark
logo: "/assets/img/logo.png"

aux_links:
  "Serveur Discord":
    - "https://discord.gg/ton-invite"

nav_external_links:
  - title: "SakurakiRP"
    url: "https://sakurakirp.github.io"